### ISSUE TITLE
How did you process the gt ?

### ISSUE THREAD

**Issue by sYANGunique1111** [ispc-lab/HRegNet#5]
Hello,

Thank you for the sharing but I found out if I transfer  your datalist (e.g. kitti sequence 08) back to the format in kitti odometry, they don't equal to each other. can you tell me how did you process to get your train data set ?

**Comment by FanLu97** [comment]
Hi, due to that the provided gt poses of KITTI datasets are noisy, we refined the gt poses using ICP algorithm (using Open3D library) with the original relative poses as initialization. Thus, the generated gt poses would not be the same as the original poses.

**Comment by sYANGunique1111** [comment]
hey, thank you for the response. continue with the question, I'd like to know if you swaped the xyz channels while computing the new relative poses. I found that KITTI datasets are in zyx form, the poses are given for xyz. Did you swap that part while refining the poses as well ?

**Comment by FanLu97** [comment]
Hello, the provided poses in KITTI dataset are with camera coordinate system. There are calibration files in KITTI dataset, which can be used to transform the poses in camera to poses in LiDAR (velodyne) coordinate system. You can refer to the description in KITTI dataset for more details. We use the calibration files rather than simply swapping the XYZ.

**Comment by sYANGunique1111** [comment]
Hello, Thank you for the answer. I think I understand the process now
